---
title: "クラウドを活用したPCの引っ越し"
format: html
---

## 背景

使用していたゲーミングPCが10才を迎え、性能と動作が怪しくなったたため、新しいゲーミングPCを購入した。<br>
それに伴いデータ移行の必要性が出たのだが、古いPCはデータ構造が汚くそのまま移行したくない。<br>
古いPCはLinux PCとして運用する予定だったため、ストレージを外して付け直しするのも面倒だった。<br>
移行用のHDD等を買うにしても、この少しの間しか使わないものにお金をかけたくない。<br>
このような状況下で、GoogleDriveでは１ヶ月間無料で容量を２Tまでアップできることを知った。<br>
そこでクラウドを活用したデータ移行を試みた。

## 準備

主に２種類の準備を行った。

* データの選別
* インストールするソフトのリストアップ

### データの選別

再取得が不可能もしくは、時間がかかるデータを中心に以下のデータをクラウドにアップロードした。

* 約500曲以上の音楽データ
* 音楽、動画の編集データ
* 写真
* ノベルゲームのセーブデータ
  * ゲームによってセーブデータの場所が異なるため、データのパスをインストールするソフトのリストに記載した。

以上のデータ(合計100G程度)を光回線の有線接続を使って1時間程度でアップロードを行った。

### インストールするソフトのリストアップ

新PCは何もソフトが入っていない状態から始める予定であった。<br>
いれる予定のフリーソフトなどをMarkdownファイルにまとめ、GitHub上にアップロードしてセットアップの効率化を図った。<br>
またおすすめのフリーソフトはyoutubeなどで調べた。

参考になった動画

* https://www.youtube.com/@pragraa/videos
* https://www.youtube.com/watch?v=WJGhky4Ikkw

## 移行

全体として４時間程度で終了した。<br>
流れは以下の通り

1. PCの初期設定（ユーザー登録など）
2. chormeのインストール
3. GoogleDriveからアップロードしたデータをダウンロード
4. Adobeなどのソフトのインストール
5. 編集ファイルをAdobeで開き、編集できることを確認
6. セーブデータをゲームファイル内に挿入し、起動確認

2までは問題なく進んだが、3の部分で合計30分程度の時間がかかった。<br>
6は問題なく、前回の続きからゲームを起動する事ができた。<br>

## 移行時のトラブル

移行工程5で一部の曲が編集ソフト上でリンク切れになる問題が発生した。<br>
原因の曲を調べると、ダウンロードして展開したファイルの3割で文字化けが発生していた。<br>
それらの曲のリンクを指定したところ、曲が認識されるようになった。<br>
曲のファイルが文字化けしたことでAdobeのソフトが認識できなくなったと考えられる。<br>

### 対策

[7zip](https://7-zip.opensource.jp/)をインストールし、ディレクトリの解凍を7zipで行った。<br>
7zipでの解凍で文字化けを5%程度まで抑える事ができた。<br>
Win11の標準解凍では30%程度文字化けがあったため、7zipの方が望ましいと考えられる。<br>
文字化けしたファイルは全ファイルの解凍後10個程度であったため、個別でリンクを指定した。<br>

### 後日談
後日対応するファイルを確認したところ、文字化けが治っていたため、時間経過で解決する問題だったのかもしれない。<br>

問題の原因を調べたところ、２つの原因があることがわかった。

* 文字コードの違い
  * Windowsでは「Shift-JIS」が、Macでは「UTF-8」が使われているため、異なるOSでデータをやり取りすると文字化けを起こす
* 解凍ソフトの問題
  * 原因は不明だが、Windows標準の解凍ソフトと、「LhacaPlus」というソフトでの解凍で文字化けが起こることがあるらしい

今回はWin10とwin11のソフト交換であり、7zipを使ったが、10程度のファイルで文字化けが起こった。<br>
問題の完全解決には至っていないが、２つの問題に対しては「7zip」か「Explzh」の活用が有効なもよう

参考サイト

* [WindowsでZIPフォルダ名やZIPファイル名が文字化けした時の対処方法](https://cadvance-review.netsbizlife.com/windows11%E3%81%A7zip%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E5%90%8D%E3%82%84zip%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D%E3%81%8C%E6%96%87%E5%AD%97%E5%8C%96%E3%81%91%E3%81%97%E3%81%9F%E6%99%82/)
* [Zipファイルを解凍すると文字化けになった！その原因と対処法は？](https://recoverit.wondershare.jp/file-repair/unzipped-zip-files-are-garbled.html)


## 反省

以下の点で反省事項がある。

1. 休憩時間を取らなかった
2. 新PCへの移行手順をまとめていなかった
3. インストールするソフトのリンクを用意していなかった
4. ディレクトリ設定法を調べて置かなかった

### 休憩時間について
PCの初期設定ではやることが多く、思った以上に時間と気力が奪われる。<br>
ここの作業は簡単なのだが、それをいくつもやると疲れが溜まってくる。<br>
そして疲れにより作業効率が極端に落ちたため、１時間に１回の休憩は必要であった。

### 移行手順書の必要性について
可能な限り思考を減らすために必要。<br>
移行時にはやるべきことが多く、疲れが溜まりやすいため疲れないようにする必要がある。<br>
インストールするソフトを決めるだけでは、どれからインストールするかを考えてしまい、時間と体力の無駄につながった。

### インストールするソフトのリンク準備
思考を減らすために必要。<br>
一部のソフトは偽のリンクなどがあるため、正しいリンクか確認するのに負担がかかった。<br>
またソフトのリンクを探すだけでも手間なので、事前にマークダウンにまとめておくべきだった。

### ディレクトリ設定について
インストール時の負荷軽減に必要。<br>
インストールする際曲はDドライブに置くなど、データ構造は事前に決めてあった。<br>
しかしwin11では標準設定でCドライブへのインストールになる仕様だった。<br>
そのためitunesなどはCドライブにインストールされ、曲もその中に入れられる事があった。<br>
それらを修正するのに時間がかかったため、ソフト等がインストール、ダウンロードされる場所の設定方法をまとめておくべきだった。

