---
title: "SAAのメモ"
format: html
---

## ECSとEKS

* ECS
  * AWSでDocker形式でアプリ開発を行う環境を提供する
* EKS
  * AWSでKubernetesで開発を行う環境を提供する

### EC2とFargeteモード

* EC2起動モード
  * EC2インスタンスで上記２つのサービスを実行する
  * サーバーレベルの細かな設定が可能
* Fargate
  * クラスター管理が不要
  * インスタンスの選択等細かい設定が不要
  * 数秒で数万個のコンテナを起動できる

## オーケストレーションサービス

* AWS Step Functions
  * Lamdaやその他のサービスをビジネスプロセスとして配列できるサーバレスのワークフロー作成、管理サービス
  * 人の手によるアクションを追加することも可能
* Simple WorkFlow(SWF）
  * 連続したステップがあるバックグラウンドジョブを構築、実行、スケールできる
  * 旧型のStep Functions
* SQS
  * ポーリング、Pull型通知をする場合はこれを使用
  * 処理の追跡は不可能


## タグ

## CNAMEレコードとエイリアスレコード

ドメイン名からIPアドレスを受け取って通信する場合、S3とRoute53を使用する。
* Aレコードとはドメイン名に対するIPV4アドレスを指定するリソースレコード、同じドメイン名に対して複数の記述が可能


* CNAMEレコード
  * CNAMEで登録した値がRoute53に送られた場合、CNAMEに紐づくレコードを返却する
  * クライアントは返却されたレコードで再度IPアドレスを問い合わせる
* ALIASレコード
  * AレコードのALIASがあればそれをAWS内でS3に問い合わせし、IPアドレスをクライアントに返す
* NSレコード
  * 外部で購入したドメインを登録する
* MXレコード
  * メールサーバを指定

## インスタンスの分類

* 汎用
  * A1、M5、T3
* コンピューティング最適化
  * C5,C6g
* メモリ最適化
  * X1,R5、ハイメモリ、Z1d
* ストレージ最適化
  * H1,D2,I3,I3en
* 高速コンピューティング
  * P3、Inf1、G4、F1

## Directory Service

* Simple AD
  * 小規模向けの簡易AD
* AD Connector
  * オンプレミス環境のADとIAMを統合
* Managed Microsoft AD
  * microsodft ADとの互換性のあるADを作成

## API Gateway

HTTP APIまたはREST APIを使用してRESTful（安全）、WebSocket(対話型) APIを作成可能

リクエストの受け口としてGatewayがあり、後続の処理を呼び出す。<br>
サーバレスかつ、DDosなどへの保護機能あり

## 静的ホスティングの手順

1. ブロックパブリック・アクセスの無効化
2. バケットポリシーで読み取り許可を設定
3. Index.htmlを配置
4. 静的ホスティングの画面で有効化

　
## リアルタイムデータ解析

* EMR
  * Apache Spark Streamingを構成することで、Kinesisからのストリーミングデータをリアルタイムに分析できる
* Kinesis Data Streams