---
title: "S3アクセス制御"
format: html
---

## 参考文献
* https://qiita.com/K5K/items/ef6a02aee760b128a25b
* https://morizyun.github.io/infrastructure/aws-s3-bucket-policy.html


## ACL（アクセスコントロールリスト）

バケット、オブジェクトに対してアクセス権を制御できる。<br>
オフにするとバケットポリシーだけでアクセス制御を行う。<br>
AWSマネジメントコンソールからアクセス許可＞アクセスコントロールリストで設定する。<br>


## バケットポリシー

バケットに対し、ユーザーごとのアップロードやダウンロードなどの操作など、複雑なアクセス制御を実現できる。<br>
バケットに対するアクセス制御を施す場合基本的にこれを使用する。<br>
JSON形式で設定する。以下はその一例で、すべてのアクセスを許可する。

``` JSON
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AddPerm",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::example-bucket/*"]
    }
  ]
}
```

* version：2012-10-17でポリシー変数を扱うことができる。
* Principal:AWSアカウントID,IAMユーザーならARNで指定
* Effect：許可する場合は`Allow`、拒否するなら`Deny`を指定
* Action：許可するアクション。`s3:GetObject`は読み込み権限
* Resource：取り扱うオブジェクトのARN。`arn:aws:s3:::example-bucket/*`で許可対象のバケットを指定
* Condition：その他の細かい設定

## IAM

ユーザー視点でアクセス制御をする場合に使う。<br>
バケットポリシーと同様にActionで操作を、Resourceで対象のバケットやオブジェクトを指定する。

## パブリックブロックアクセス

パブリックに公開することを防止する時に有効化する。デフォルトでは有効になっている。<br>
S3はインターネット上で公開する事ができるが、静的ウェブホスティングの有効化以外に、
パブリックブロックアクセスの許可が必要。<br>
その他にも上記のもので１つでも拒否が設定されている場合はアクセスができない。