---
title: "AWS初期設定"
format: html
---

## アカウント作成

AWSのアカウントを作成する。作成に必要なものは以下の通り

* メールアドレス
* クレジットカード
* 電話番号

アカウントの作成手順は以下の通り<br>
基本的に求められる情報を入力すれば問題ない。最後の**プラン選択によってはお金がかかる場合がある**ので注意。

1. AWSのホームページへ移動し、左上の**サインアップを完了する**をクリック
2. Emailアドレス、パスワード、AWSアカウント名を入力
3. 住所、電話番号を入力
4. クレジットカードの登録
5. SMSによる本人確認
6. サポートプランの選択
   1. ３種のプランがあるが、勉強目的での利用ならベーシックプランを選択

アカウント作成後はAWSのホームページに再度アクセスし、左上のコンソールにサインインから先程設定した情報を入力しログインする。


## 料金アラートの設定

AWSは**従量課金性のサービス**であるため、意図せず高額の請求が来てしまうことがある。<br>
そこで請求額が一定額を上回った場合、指定したメールアドレスに通知をする設定を行う。

1. AWSにログイン後 `左上のアカウント> Biling and Cost Management `をクリック
2. 左の再度バーを下へスクロールし、設定の下にある`請求設定`をクリック
3. `請求書の送信設定の編集`をクリックし、`Eメールで配信される PDF 請求書`にチェックを入れ、更新をクリック
4. `AWS 無料利用枠アラート`のEメールアドレスにアラートを受診するアドレスを入力
5. `CloudWatch 請求アラート`を受信するにチェックを入れる
6. 更新をクリック

### CloudWatchの設定

1. Regionがバージニア北部に変更
2. 上の検索欄にCloudWatchと入力し、検索
3. `アラームの作成`をクリック
4. `メトリクスの選択＞請求＞概算合計請求額＞USDにチェック＞メトリクス選択`
5. アラートの条件設定`条件＞静的、より大きいを選択＞USDにアラートを出したい金額を入力＞次へ`
6. 通知先の設定`アラーム状態`、`新しいトピックの作成＞トピック名、アラートを受け取るアドレスの入力＞トピックの作成`
7. 指定したアドレスに届いたメールのURLをクリックして認証
8. AWSの画面に戻り、`既存のトピックを選択>作成したトピック名をクリック＞次へ`
9. アラーム名を入力し、次へをクリック
10. 設定した条件を確認して問題なければ`アラームの作成`をクリック
11. アラームの一覧画面へ遷移し、状態がOKになれば完了

**注意**<br>
* 5でアラームの感覚を設定できるが、1分単位にすると有料となる。（デフォルトは6時間）
* 11で状態がOKにならない場合は時間をおいてページを更新する

**参考文献**
* https://zenn.dev/myatti/articles/a4d6333ea9edf9


## IAMユーザーの作成

AWSのベストプラクティスではIAMユーザーという一般利用用のユーザーを作成し作業をすることが望ましいとされている。<br>
これまでの作業はルートユーザーであるため、作業用のIAMユーザーを作成する。

## 操作ログの記録

##