---
title: "AWSストレージ"
format: html
---

## Amazon S3 (Amazon Sinmple Storage Service)

AWS上で使われるストレージのこと。オブジェクトストレージに分類される。<br>
バケットと呼ばれる場所にオブジェクト（ファイル）を格納する。<br>
バケットのデータは異なる3箇所以上のアベイラビリティーゾーンに自動で保存される。<br>
データは99.999999999％の耐久性が保証されている。(イレブンナイン)<br>
料金は使用する容量や取り出し頻度で決まる。<br>
ストレージだけでなく静的ウェブサイトのホストも行える

### 用語解説

* バケット
  * オブジェクト（ファイル）格納する場所
  * バケットには全世界でユニークな名前をつける必要がある。<br>

オブジェクトは**キー**と呼ばれるパスで指し示される。<br>
このキーの作成にバケットの名前が使われるため、ユニークな名前をつける必要がある。

### ストレージクラス

S3ではアクセス頻度と、ストレージの性能に応じてストレージクラスが設定されている。<br>
ストレージクラスによって料金が異なるため、用途に応じたクラスの選択が必要

ストレージクラスとコスト<br>

* S3 標準
  * 頻繁にアクセスされるデータの格納に適している
  * デフォルトで選択されるストレージ、高耐久、高可用性を持つ
* S3 標準-低頻度アクセス
  * アクセス頻度の低いデータの格納に適している
  * データの取り出しに料金が発生するストレージ
* S3 Glacier
  *  データのアーカイブに適したストレージ
  *  データの取り出しに料金がかかるのに加え、取り出すのにも時間がかかる
* S3 Glacier DEEP
   *  年に１、２回しか取り出さないデータのアーカイブに適したストレージ
   *  コストは最も低いが、取り出しに最大１２時間を要する

### セキュリティ保護

S3はインターネットから直接接続されるため、セキュリティ対策が必要。<br>
不特定多数のユーザーからのアクセスは拒否されている。<br>

アクセスコントロールとして以下の物がある。

* ユーザーポリシー
  * IAMユーザーに対してアクセス権限が設定できる
* バケットポリシー
  * バケット単位でアクセスの権限設定ができる

## RDS



## DynamoDB

##  


