---
title: "Web三層モデル"
format: html
---
## 参考文献

https://qiita.com/kamihork/items/49e2a363da7d840a4149
https://qiita.com/thirai67/items/24517ce80d402bb152cf

## 概要

Web三層モデルとは、WebアプリをWebサーバー、APサーバー、DBサーバーに分けて構築するモデルのこと。<br>
一般的に各層ごとにサーバーを用意し、Webサーバーを外部に公開し、AP、DBサーバーはWebサーバ、もしくは内部からのアクセスのみ許可する。<br>
これによって外部処理と内部処理を分けることができ、アプリの処理方式や顧客データなど、利用者に見せたくない情報を隠すことができる。<br>
なおWeb三層を実装するのに必要な機能はLinuxなどのOSには搭載されていないため、Web、AP、DBに必要な機能をまとめたソフトウェアをインストールする必要がある。<br>
そしてWeb、AP、DBを実装するのに必要なソフトウェアの総称をミドルウェアと呼ぶ。



## Webサーバ

外部ネットからアクセスを受け、HTMLを返す。<br>
Webページにアクセスをする場合、Webサーバに向けて表示するページを要求する。<br>
この要求を**リクエスト**と呼び、それに対しWebサーバからページを返されることを**レスポンス**と呼ぶ。<br>
Webサーバを実装するためのソフトウェアとして **Apache**や**Nginx**が存在する。<br>
Webアプリを作成する場合は、Apacheなどをインストールしその中で指定の場所に返却用のhtmlファイルを配置する。<br>
利用者は配置したhtmlファイルに対してリクエストを行うことで画面の閲覧が可能になる。<br>


### Webサーバの役割

静的コンテンツを返却することと、APサーバへ処理を要求することの2つがある。<br>
静的コンテンツとはWebサイトのトップ画面などの事前に用意されたものを示す。<br>
Webサーバでは利用者全員に共通する画面を事前に用意しておき、それを利用者から要求があった際に返却する。<br>
しかしこの方法では人それぞれ異なる画面を表示することができない。<br>
例えばAmazonなどで検索を行い、それによって表示される画面は人によって異なる。<br>
このような画面を利用者ごとの要求に応じて表示するには、画面を要求に応じて作る必要がある。<br>
画面を作る処理をWebサーバで行うことはできないため、「要求に応じた画面を作って」という要求を次のAPサーバへ送る。<br>


### 主要なWebサーバのミドルウェア

#### Apach(アパッチ)

20年間利用されているWebサーバのOSS（オープンソースソフトウェアで、誰でも無料で使える）<br>
長年使用されているため、信頼性が高い。また機能拡張も用意である。<br>
マルチプロセスモデルを採用しており、接続ごとにプロセスをコピーするため、重い処理が他のプロセスに影響を与えず重い処理が得意。<br>
一方でメモリの使用量が多くなりやすいデメリットがあり、接続数が少ない場合に向いている。<br>

#### Nginx(エンジンエックス)

同時接続数が1万台以上を超えるとサーバが処理しきれなくなる問題があり、大量の同時接続や配信に耐えられるように設計された。<br>
Apacheよりも同時接続が多く、Apacheの10~100倍程度の同時接続を処理できる。<br>
また大量のアクセスを複数のサーバに分散して処理する負荷分散の機能を持つ。<br>
処理方式はイベント駆動であり、１つのスレッドでループを使いを行うため、処理の上限数は多い。<br>
しかし1つの処理が遅れるとその後の処理も遅れるため、重い処理には向かない。

## APサーバの役割

Webサーバから受けた要求に応じて画面の作成またはプログラムを処理する。<br>
検索結果の画面を作成するにはデータが蓄積されたDBに対し、検索処理を実行し、その結果をHTMLに含める必要がある。<br>
APサーバでは「DBから検索を行う」などのプログラムを用意し、それをWebサーバからの要求に応じて実行し、画面を作成する。<br>
ミドルウェアとして**Tomcat**などが用いられる。<br>

なお要求に応じて作られる画面は、事前に用意された静的コンテンツと対比し、動的コンテンツと呼ばれる。

## DBサーバの役割

データ保管を行う。<br>
データの管理とデータの操作を行う機能を持ち、SQLというプログラム言語を用いてそれらを行う。<br>
DBにはデータの更新や削除など、保管したデータに対し変更が行われる。<br>
この際利用者によってデータの内容が異なると問題が生じるため、
更新が行われた場合はそれ以降は利用者全員が更新されたあとのものを使用するといった特性を持つ。